<?php
/**
 * @var $this Strell_Log_Browser
 */
?>
<style>
    .message-container{
        border: solid 1px #cccccc;
        width: 800px;
        margin-left: auto;
        margin-right: auto;
        padding: 10px;
        margin-bottom: 10px;
    }
    .message-container header{
        border: solid 1px #cccccc;
        padding: 10px;
        background: #dcdcdc;
        font: normal 18px Arial;
    }

    .message-container pre{
        display: block;
        text-align: left;
        font: normal 14px Arial;
        padding: 10px;
        background: ghostwhite;
        margin-top: 10px;
    }
</style>
<div class="message-container">
    <header><?php echo $this->getMessageHeader()?></header>
    <pre><?php echo $this->getMessageHtml()?></pre>
</div>
